"""Hooks around graphs, nodes, models and tools, and the built-in middleware.

Subclass `Middleware` and override the hooks you need. Built in: tool
approvals, tool-call limits, summarization, to-do lists, skills and memory.
See [Middleware](../../concepts/middleware.md).
"""

from nodestep.exceptions import ToolDeniedError
from nodestep.middleware.base import (
    GraphMiddlewareContext,
    HookName,
    Middleware,
    ModelMiddlewareContext,
    NodeMiddlewareContext,
    Replacement,
    ToolMiddlewareContext,
    collect_middleware_tools,
    run_after_hooks,
    run_before_hooks,
)
from nodestep.middleware.interrupt import (
    InterruptRule,
    ToolDecision,
    ToolInterrupt,
    ToolInterruptMiddleware,
    all_fields,
    any_field,
    eq,
    ge,
    gt,
    le,
    lt,
    matches,
    should_interrupt,
)
from nodestep.middleware.memory import (
    BaseMemory,
    FilesystemMemory,
    Memory,
    MemoryConfigError,
    MemoryDeleteResult,
    MemoryListResult,
    MemorySearchResult,
)
from nodestep.middleware.skills import (
    BaseSkills,
    FilesystemSkills,
    LoadedSkill,
    Skill,
    SkillCatalog,
    SkillConflictError,
    SkillFormatError,
    SkillNotFoundError,
)
from nodestep.middleware.summarization import (
    ApproximateTokenCounter,
    FixedTokenTrigger,
    MessageCountTrigger,
    RecentMessagesPolicy,
    RecentTokensPolicy,
    SummarizationDecision,
    SummarizationMiddleware,
    SummarizationResult,
    SummarizationTrigger,
    TokenCounter,
    TokenLimitTrigger,
)
from nodestep.middleware.todolist import (
    TodoItem,
    TodoItemState,
    TodoListMiddleware,
    TodoListMiddlewareError,
    TodoListSnapshot,
)
from nodestep.middleware.tool_limit import ToolLimitMiddleware

__all__ = [
    "ApproximateTokenCounter",
    "BaseMemory",
    "BaseSkills",
    "FilesystemMemory",
    "FilesystemSkills",
    "FixedTokenTrigger",
    "GraphMiddlewareContext",
    "HookName",
    "InterruptRule",
    "LoadedSkill",
    "Memory",
    "MemoryConfigError",
    "MemoryDeleteResult",
    "MemoryListResult",
    "MemorySearchResult",
    "MessageCountTrigger",
    "Middleware",
    "ModelMiddlewareContext",
    "NodeMiddlewareContext",
    "RecentMessagesPolicy",
    "RecentTokensPolicy",
    "Replacement",
    "Skill",
    "SkillCatalog",
    "SkillConflictError",
    "SkillFormatError",
    "SkillNotFoundError",
    "SummarizationDecision",
    "SummarizationMiddleware",
    "SummarizationResult",
    "SummarizationTrigger",
    "TodoItem",
    "TodoItemState",
    "TodoListMiddleware",
    "TodoListMiddlewareError",
    "TodoListSnapshot",
    "TokenCounter",
    "TokenLimitTrigger",
    "ToolDecision",
    "ToolDeniedError",
    "ToolInterrupt",
    "ToolInterruptMiddleware",
    "ToolLimitMiddleware",
    "ToolMiddlewareContext",
    "all_fields",
    "any_field",
    "collect_middleware_tools",
    "eq",
    "ge",
    "gt",
    "le",
    "lt",
    "matches",
    "run_after_hooks",
    "run_before_hooks",
    "should_interrupt",
]
